const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Dictionary,
		C3.Plugins.List,
		C3.Plugins.NinePatch,
		C3.Behaviors.Pin,
		C3.Behaviors.Tween,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.BinaryData,
		C3.Plugins.TextBox,
		C3.Plugins.sliderbar,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.Timer,
		C3.Behaviors.Flash,
		C3.Behaviors.LOS,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Plugins.gamepad,
		C3.Plugins.Camera3D,
		C3.Plugins.LocalStorage,
		C3.Plugins.Function,
		C3.Behaviors.EightDir,
		C3.Behaviors.Persist,
		C3.Behaviors.MoveTo,
		C3.Plugins.AJAX,
		C3.Plugins.Flowchart,
		C3.Plugins.Multiplayer,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Plugins.Shape3D,
		C3.Plugins.Timeline,
		C3.Plugins.Particles,
		C3.Behaviors.jumpthru,
		C3.Plugins.Tilemap,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Behaviors.Anchor,
		C3.Behaviors.DragnDrop,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Browser,
		C3.Plugins.Photon,
		C3.Behaviors.Rotate,
		C3.Plugins.Date,
		C3.Plugins.progressbar,
		C3.Plugins.advert,
		C3.Plugins.googleplay,
		C3.Plugins.SVGPicture,
		C3.Plugins.Bluetooth,
		C3.Behaviors.Follow,
		C3.Plugins.Button,
		C3.Plugins.Share,
		C3.Plugins.FileSystem,
		C3.Plugins.filechooser,
		C3.Behaviors.Orbit,
		C3.Plugins.video,
		C3.Plugins.AdvancedRandom,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Json,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.Dictionary.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Dictionary.Exps.AsJSON,
		C3.Plugins.Dictionary.Cnds.IsEmpty,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Dictionary.Cnds.ForEachKey,
		C3.Plugins.List.Acts.AddItem,
		C3.Plugins.Dictionary.Exps.CurrentKey,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Audio.Acts.AddPhaserEffect,
		C3.Plugins.Audio.Acts.AddFlangerEffect,
		C3.Plugins.LocalStorage.Cnds.IsPersistent,
		C3.Plugins.LocalStorage.Acts.RequestPersistent,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.PlatformInfo.Cnds.IsOnAndroid,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.gamepad.Exps.GamepadCount,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.TextBox.Acts.SetBlur,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.LocalStorage.Cnds.CompareValue,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Arr.Cnds.CompareX,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.LocalStorage.Acts.RemoveItem,
		C3.Plugins.List.Exps.ItemTextAt,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.List.Exps.ItemCount,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Dictionary.Exps.KeyCount,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.gamepad.Cnds.OnGamepadConnected,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.Keyboard.Exps.StringFromKeyCode,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.Keyboard.Cnds.IsKeyCodeDown,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Keyboard.Cnds.OnKeyCode,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Photon.Exps.MyActorNr,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.Photon.Acts.raiseEvent,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Pin.Acts.Unpin,
		C3.Plugins.Photon.Acts.disconnect,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetY,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Plugins.Spritefont2.Acts.SubInstanceVar,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar,
		C3.Behaviors.Pin.Cnds.IsPinned,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.TiledBg.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.TiledBg.Acts.AddInstanceVar,
		C3.Plugins.Spritefont2.Cnds.IsVisible,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnFrameChanged,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Dictionary.Cnds.CompareValue,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.gamepad.Acts.VibrateDualRumble,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Cnds.OnCleared,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Keyboard.Exps.LastKeyCode,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.TextBox.Acts.SetText,
		C3.Plugins.System.Cnds.OnSaveComplete,
		C3.Plugins.Share.Acts.Share,
		C3.Plugins.System.Exps.savestatejson,
		C3.Plugins.Browser.Acts.InvokeDownloadString,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.System.Acts.LoadStateJSON,
		C3.Plugins.filechooser.Exps.FileURLAt,
		C3.Plugins.filechooser.Acts.Clear,
		C3.Plugins.filechooser.Cnds.OnChanged,
		C3.Plugins.System.Exps.zeropad,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.BinaryData.Acts.SetFromBase64,
		C3.Plugins.Sprite.Acts.LoadURL,
		C3.Plugins.BinaryData.Exps.GetURL,
		C3.Plugins.Sprite.Acts.AddRemoveAnimationFrame,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.System.Exps.layerscrollx,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Sprite.Acts.SetZElevation,
		C3.Plugins.System.Exps.projectversion,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.Photon.Acts.connect,
		C3.Plugins.Photon.Exps.ActorNr,
		C3.Behaviors.Platform.Acts.SetDefaultControls,
		C3.Plugins.Photon.Acts.setRegion,
		C3.Plugins.Photon.Cnds.onError,
		C3.Plugins.Photon.Acts.joinRandomRoom,
		C3.Plugins.Photon.Cnds.onDisconnected,
		C3.Plugins.Photon.Cnds.isInLobby,
		C3.Plugins.Photon.Cnds.onJoinRandomRoomNoMatchFound,
		C3.Plugins.Photon.Acts.createRoom,
		C3.Plugins.Photon.Acts.setMyRoomMaxPlayers,
		C3.Plugins.Photon.Cnds.onJoinRoom,
		C3.Plugins.Photon.Cnds.onEvent,
		C3.Plugins.Photon.Exps.ActorNrAt,
		C3.Plugins.Photon.Cnds.onActorJoin,
		C3.Plugins.Photon.Acts.setMyRoomIsOpen,
		C3.Plugins.Photon.Acts.setMyRoomIsVisible,
		C3.Plugins.Photon.Exps.EventData,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Cnds.OnSignal,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.Button.Cnds.HasTags,
		C3.Plugins.Photon.Acts.reset,
		C3.Plugins.Button.Cnds.IsVisible,
		C3.Behaviors.Sin.Exps.Value,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.Physics.Acts.SetPreventRotate,
		C3.Behaviors.Physics.Acts.SetFriction,
		C3.Behaviors.Physics.Acts.SetElasticity,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Plugins.Audio.Acts.SetPlaybackRate,
		C3.Plugins.Audio.Acts.RemoveEffects,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Behaviors.Physics.Acts.SetDensity,
		C3.Behaviors.Physics.Exps.Density,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.Platform.Exps.Gravity,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Exps.JumpStrength,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Platform.Acts.SetAcceleration,
		C3.Behaviors.Platform.Acts.SetDeceleration,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Particles.Acts.SetInstanceVar,
		C3.Plugins.Particles.Acts.SetDefaultColor,
		C3.Plugins.Particles.Cnds.CompareInstanceVar,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.PickParent,
		C3.Plugins.Sprite.Exps.AnimationFrameTag,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.RemoveFromParent,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Behaviors.Bullet.Cnds.CompareTravelled,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Follow.Acts.StopFollowing,
		C3.Behaviors.Follow.Acts.ClearHistory,
		C3.Behaviors.Follow.Acts.SetPaused,
		C3.Behaviors.Follow.Acts.SetFollowingProperty,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Behaviors.Platform.Exps.Speed,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Plugins.Sprite.Exps.TagAt,
		C3.Behaviors.Platform.Exps.VectorY,
		C3.Behaviors.Platform.Exps.MovingAngle,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Sprite.Acts.RotateClockwise,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.TiledBg.Acts.MoveToBottom,
		C3.Plugins.TiledBg.Acts.SetTowardPosition,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Behaviors.Follow.Cnds.IsFollowingObject,
		C3.Plugins.Particles.Acts.ChangeTags,
		C3.Plugins.Particles.Acts.ZMoveToObject,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Particles.Cnds.IsSpraying,
		C3.Plugins.Particles.Acts.SetSpraying,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.Sprite.Cnds.IsFlipped,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Behaviors.Physics.Acts.ApplyImpulseAtAngle,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Behaviors.Bullet.Acts.SetBounceOffSolids,
		C3.Behaviors.Bullet.Acts.SetAcceleration,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Plugins.Date.Exps.GetHours,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Date.Exps.GetMinutes,
		C3.Plugins.Particles.Acts.SetPosToObject,
		C3.Plugins.Particles.Acts.SetPos,
		C3.Behaviors.Physics.Acts.CreateRevoluteJoint,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Date.Cnds.CompareDateStrings,
		C3.Plugins.Timeline.Cnds.IsPlayingByTags,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Plugins.Timeline.Cnds.OnKeyframeReached,
		C3.Plugins.advert.Cnds.OnRewardedComplete,
		C3.Plugins.advert.Cnds.OnRewardedCancelled,
		C3.Plugins.advert.Cnds.OnRewardedFailedToLoad,
		C3.Plugins.Timeline.Cnds.IsAnyPlaying,
		C3.Plugins.advert.Cnds.IsRewardedLoaded,
		C3.Plugins.advert.Cnds.IsShowingRewarded,
		C3.Plugins.advert.Acts.CreateRewarded,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Dictionary.Exps.CurrentValue,
		C3.Plugins.Dictionary.Acts.AddInstanceVar,
		C3.Plugins.TiledBg.Acts.SetZElevation,
		C3.Plugins.Audio.Exps.PlaybackTime,
		C3.Plugins.Audio.Exps.Duration,
		C3.Plugins.Dictionary.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetEffectEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.find,
		C3.Plugins.Arr.Cnds.IsEmpty,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Date.Exps.GetDay,
		C3.Plugins.Dictionary.Acts.DeleteKey,
		C3.Plugins.List.Acts.LoadFromJsonString,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.List.Acts.Remove,
		C3.Plugins.List.Exps.AsJSON,
		C3.Plugins.Timeline.Cnds.OnTimelineFinishedByTags,
		C3.Plugins.Spritefont2.Exps.LayerName,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.Plugins.System.Cnds.IsNaN,
		C3.Behaviors.Physics.Acts.ApplyTorqueToPosition,
		C3.Plugins.Browser.Acts.Vibrate,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.video.Acts.Play,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Particles.Acts.SetXRandomiser,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Cnds.PickByUID,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Behaviors.Follow.Acts.SetEnabled,
		C3.Behaviors.Follow.Acts.LoadHistoryJSON,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PauseTimelineByTags,
		C3.Plugins.List.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.List.Acts.SubInstanceVar,
		C3.Plugins.List.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetBoolInstanceVar,
		C3.Plugins.TiledBg.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.TiledBg.Acts.SetEffectEnabled,
		C3.Plugins.TiledBg.Acts.SetEffectParam,
		C3.Plugins.System.Exps.layoutscale,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetSpeed,
		C3.Plugins.Timeline.Acts.PlayTimelineByName,
		C3.Plugins.Spritefont2.Acts.SetCharacterWidth,
		C3.Plugins.System.Exps.rgbex,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsEffectEnabled,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.Plugins.TiledBg.Cnds.IsBetweenAngles,
		C3.Plugins.Particles.Acts.SetVisible,
		C3.Plugins.Timeline.Acts.StopAllTimelines,
		C3.Plugins.Timeline.Acts.ResumeTimelineByTags,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.video.Acts.SetSource2,
		C3.Plugins.video.Acts.SetVolume,
		C3.Plugins.video.Cnds.OnPlaybackEvent,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.Pause,
		C3.Plugins.AdvancedRandom.Acts.CreateProbabilityTable,
		C3.Plugins.AdvancedRandom.Acts.AddProbabilityEntry,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.AdvancedRandom.Acts.SetProbabilityTable,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.AdvancedRandom.Exps.Weighted,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Audio.Acts.PlayAtPositionByName,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Acts.SetMaxSpeed,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Photon.Cnds.onActorLeave,
		C3.Behaviors.Physics.Cnds.IsEnabled,
		C3.Behaviors.Platform.Cnds.IsEnabled,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Exps.AnimationSpeed,
		C3.Plugins.Sprite.Cnds.IsClockwiseFrom,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.NinePatch.Cnds.PickDistance,
		C3.Plugins.TextBox.Exps.X,
		C3.Plugins.TextBox.Exps.Y,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Cnds.HasTags,
		C3.Plugins.NinePatch.Acts.SubInstanceVar,
		C3.Plugins.NinePatch.Acts.AddInstanceVar,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.Timeline.Acts.UnsetInstances,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Timeline.Acts.PauseAllTimelines,
		C3.Plugins.Timeline.Cnds.IsAnyPaused,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Spritefont2.Acts.SetZElevation,
		C3.Plugins.Sprite.Cnds.CompareZElevation,
		C3.Plugins.Sprite.Exps.ZElevation,
		C3.Plugins.TextBox.Acts.SetFocus,
		C3.Plugins.TextBox.Cnds.IsFocused,
		C3.Plugins.Photon.Cnds.onJoinedLobby,
		C3.Plugins.Photon.Acts.requestLobbyStats,
		C3.Plugins.Spritefont2.Acts.AppendText,
		C3.Plugins.Photon.Cnds.onLobbyStats,
		C3.Plugins.Photon.Exps.LobbyStatsCount,
		C3.Plugins.System.Exps.mid,
		C3.Plugins.Photon.Cnds.isJoinedToRoom,
		C3.Plugins.Photon.Acts.joinRoom,
		C3.Plugins.System.Exps.uppercase,
		C3.Plugins.Photon.Exps.ActorCount,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Behaviors.solid.Cnds.IsEnabled,
		C3.Behaviors.solid.Acts.SetEnabled,
		C3.Plugins.Timeline.Cnds.OnAnyTimelineStarted,
		C3.Plugins.Timeline.Exps.TimelineName,
		C3.Plugins.Sprite.Acts.RotateCounterclockwise,
		C3.Plugins.Browser.Acts.Close,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Acts.SnapshotCanvas,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.PlatformInfo.Exps.DevicePixelRatio,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.PlatformInfo.Exps.CanvasDeviceHeight,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.canvassnapshot,
		C3.Plugins.Timeline.Cnds.OnTimelineStartedByTags,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Behaviors.Flash.Cnds.OnFlashEnded,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Exps.layerparallaxy,
		C3.Plugins.Timeline.Cnds.IsPausedByTags,
		C3.Plugins.Sprite.Cnds.IsCollisionEnabled,
		C3.Behaviors.Rotate.Exps.Speed,
		C3.Plugins.Photon.Exps.MasterActorNr,
		C3.Plugins.System.Exps.float,
		C3.Behaviors.solid.Acts.SetTags,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Behaviors.MoveTo.Acts.SetRotateSpeed,
		C3.Plugins.Timeline.Exps.Value,
		C3.Behaviors.Fade.Acts.SetWaitTime,
		C3.Plugins.Particles.Acts.SetInitSize,
		C3.Plugins.sliderbar.Acts.SetValue,
		C3.Plugins.List.Acts.Select,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Arr.Acts.JSONDownload,
		C3.Plugins.filechooser.Acts.Click,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.Sprite.Exps.AsJSON,
		C3.Plugins.Sprite.Acts.LoadFromJsonString,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Acts.MoveToTop,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxMidY,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.AJAX.Acts.SetResponseBinary,
		C3.Plugins.BinaryData.Exps.GetBase64,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.sliderbar.Exps.Value,
		C3.Plugins.TiledBg.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.TextBox.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVAlign,
		C3.Plugins.Spritefont2.Acts.SetHAlign,
		C3.Plugins.List.Acts.Clear,
		C3.Plugins.TextBox.Cnds.HasTags,
		C3.Plugins.List.Acts.Destroy,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Spritefont2.Cnds.CompareY,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.List.Exps.SelectedText,
		C3.Plugins.List.Cnds.CompareSelectedText,
		C3.Plugins.TextBox.Cnds.CompareInstanceVar,
		C3.Plugins.List.Cnds.OnSelectionChanged,
		C3.Plugins.List.Exps.SelectedIndex,
		C3.Plugins.TextBox.Cnds.PickByUID,
		C3.Plugins.System.Cnds.OnCanvasSnapshot,
		C3.Plugins.Timeline.Cnds.OnAnyTimelineFinished,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Plugins.System.Cnds.IsBetweenAngles,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Dictionary.Cnds.CompareCurrentValue,
		C3.Plugins.System.Exps.layerscrolly,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Spritefont2.Cnds.IsRunningTypewriterText
	];
};
self.C3_JsPropNameTable = [
	{Arcaderoad: 0},
	{colors: 0},
	{Dictionary: 0},
	{Keys: 0},
	{KEYS2: 0},
	{List: 0},
	{List2: 0},
	{List_Museom: 0},
	{List_OST: 0},
	{Logros: 0},
	{Logros2: 0},
	{MUSEOM: 0},
	{Names: 0},
	{Neims: 0},
	{P_Char: 0},
	{P_museo: 0},
	{values: 0},
	{P_OnlyforOSTAchiev: 0},
	{P_Ost: 0},
	{P_Stages: 0},
	{Stadistics: 0},
	{Stats: 0},
	{Upk: 0},
	{ArcadeArray: 0},
	{ArcadeNumbers: 0},
	{Colorsget: 0},
	{codes: 0},
	{Online_Levels: 0},
	{Online_Data: 0},
	{ITEMS: 0},
	{itemsActivated: 0},
	{Avatararry: 0},
	{Avatarkeys: 0},
	{LogrosRecompensas: 0},
	{peloreto: 0},
	{E_array2: 0},
	{Moveset: 0},
	{ColArcLogros: 0},
	{grasadial: 0},
	{Pin: 0},
	{Tween: 0},
	{E_9patch: 0},
	{E_Arrow: 0},
	{E_Bg: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{E_camera: 0},
	{Width_Save: 0},
	{Height_Save: 0},
	{Angle_Save: 0},
	{PositionX_Save: 0},
	{PositionY_Save: 0},
	{Animation_Save: 0},
	{Frame_Save: 0},
	{seleccionado: 0},
	{Data_Save: 0},
	{Anm_Save: 0},
	{Lay_Save: 0},
	{OBJTYPE: 0},
	{OID: 0},
	{Eventos: 0},
	{EventCount: 0},
	{ID: 0},
	{Move: 0},
	{Movecount: 0},
	{Moveindex: 0},
	{MoveBackwards: 0},
	{propieties: 0},
	{RotSet: 0},
	{Pinnabl: 0},
	{ConditionNm: 0},
	{ConditionCount: 0},
	{val: 0},
	{E_obj: 0},
	{Less_Height: 0},
	{Less_size: 0},
	{Less_Witdh: 0},
	{Plus_Height: 0},
	{Plus_size: 0},
	{Plus_Witdh: 0},
	{Rotate_Left: 0},
	{Rotate_Right: 0},
	{SaveButton: 0},
	{SaveButton2: 0},
	{SaveButton3: 0},
	{Framearray: 0},
	{BinaryData: 0},
	{E_array: 0},
	{Delete: 0},
	{Clone: 0},
	{flip: 0},
	{Mirror: 0},
	{EdgeSpawner: 0},
	{Color: 0},
	{EditorColor: 0},
	{EditorInput: 0},
	{EditorSlC1: 0},
	{EditorSlC2: 0},
	{EditorSlC3: 0},
	{EditEditor: 0},
	{EditorInput2: 0},
	{EventArray: 0},
	{ID2: 0},
	{Val: 0},
	{Eventinput: 0},
	{Eventinput2: 0},
	{EDITOR: 0},
	{ChangeLayer: 0},
	{Sine: 0},
	{ola3: 0},
	{Mascotas: 0},
	{pets: 0},
	{Slowmo: 0},
	{Slowmo2: 0},
	{SaveX: 0},
	{SaveY: 0},
	{Recup: 0},
	{jump: 0},
	{State: 0},
	{Attack: 0},
	{Charge: 0},
	{lastdir: 0},
	{per: 0},
	{BULLET: 0},
	{Potencia: 0},
	{PLAYER: 0},
	{fallind: 0},
	{shield: 0},
	{Speed: 0},
	{cooldown: 0},
	{movecooldown: 0},
	{C: 0},
	{char: 0},
	{JUMPSTREGHT: 0},
	{JumpStreght2: 0},
	{VIDAS: 0},
	{Anglepunch: 0},
	{Daño: 0},
	{raw: 0},
	{JumpNumb: 0},
	{InitialJump: 0},
	{WD: 0},
	{DEATH: 0},
	{Stun: 0},
	{SPECIAL: 0},
	{EXTRADM: 0},
	{EXTRAPW: 0},
	{EXTRASPEED: 0},
	{POINT: 0},
	{LEVEL: 0},
	{LOCK: 0},
	{MV: 0},
	{AT: 0},
	{CPU: 0},
	{AT2: 0},
	{MV1: 0},
	{ACTOR: 0},
	{COMBO: 0},
	{Special1: 0},
	{Special2: 0},
	{Special3: 0},
	{Special4: 0},
	{VX: 0},
	{VY: 0},
	{MODE: 0},
	{Clon: 0},
	{item: 0},
	{ItemType: 0},
	{Flooranim: 0},
	{b_pressin: 0},
	{ACTION: 0},
	{action2: 0},
	{BULLET2: 0},
	{vxx: 0},
	{vyy: 0},
	{TAMAÑO: 0},
	{Platform: 0},
	{Physics: 0},
	{Timer: 0},
	{Flash: 0},
	{LineOfSight: 0},
	{player: 0},
	{Solid: 0},
	{Sprite2: 0},
	{solid: 0},
	{Actor: 0},
	{COLOR: 0},
	{delay: 0},
	{clon: 0},
	{mask: 0},
	{Keyboard: 0},
	{Per: 0},
	{Sprite: 0},
	{dmg: 0},
	{dir: 0},
	{anglepunch: 0},
	{destroy: 0},
	{Ox: 0},
	{ONLINE: 0},
	{hitbox: 0},
	{player2: 0},
	{Sprite3: 0},
	{TiledBackground: 0},
	{menu: 0},
	{Men_Button: 0},
	{SpriteFont: 0},
	{Gamepad: 0},
	{Sprite5: 0},
	{"3DCamera": 0},
	{LocalStorage: 0},
	{Function: 0},
	{place: 0},
	{Sprite6: 0},
	{trans: 0},
	{Sprite7: 0},
	{CHAR: 0},
	{Name: 0},
	{Secret: 0},
	{Charslot: 0},
	{Sprite9: 0},
	{TOWER: 0},
	{Menu: 0},
	{Sprite11: 0},
	{Sprite8: 0},
	{Scale: 0},
	{TiledBackground2: 0},
	{"8Direction": 0},
	{Hand: 0},
	{Cke: 0},
	{Persist: 0},
	{Char_Selector: 0},
	{Sprite12: 0},
	{charescreen: 0},
	{CAMPRINCIPAL: 0},
	{Camsec1: 0},
	{Camsec2: 0},
	{MoveTo: 0},
	{CAMPRINCIPAL2: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{TiledBackground3: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Saved: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{OnOff: 0},
	{Camsec3: 0},
	{Camsec4: 0},
	{particulas: 0},
	{flash: 0},
	{Id: 0},
	{Ud_line: 0},
	{ox: 0},
	{SpriteFont2: 0},
	{id: 0},
	{ud_rombo: 0},
	{icon: 0},
	{edge: 0},
	{stockhud: 0},
	{AJAX: 0},
	{grab: 0},
	{Sprite23: 0},
	{Sprite24: 0},
	{FlowchartController: 0},
	{spawner: 0},
	{Multiplayer: 0},
	{DM: 0},
	{PER: 0},
	{Trail: 0},
	{td: 0},
	{Bullet: 0},
	{proyectil: 0},
	{Player: 0},
	{Pointer: 0},
	{Percentaje: 0},
	{P1mark: 0},
	{P2mark: 0},
	{P3mark: 0},
	{P4mark: 0},
	{deatheffect: 0},
	{deathzone: 0},
	{Audio: 0},
	{St_BackPlanes: 0},
	{cloud: 0},
	{cloud2: 0},
	{titlecard: 0},
	{St_Lit3: 0},
	{Men_Back: 0},
	{TEXT: 0},
	{TEXT2: 0},
	{StageImage: 0},
	{"3DShape": 0},
	{"3DShape2": 0},
	{StageView: 0},
	{Plane: 0},
	{TimelineController: 0},
	{Particles2: 0},
	{Particles: 0},
	{forest: 0},
	{Jumpthru: 0},
	{Mushrooms: 0},
	{St_Backtrees: 0},
	{Sprite30: 0},
	{TiledBackground4: 0},
	{Sprite31: 0},
	{TiledBackground5: 0},
	{T78B: 0},
	{Particle_Leaf: 0},
	{raindrop: 0},
	{Particle_rain: 0},
	{St_ouse: 0},
	{St_BackBuilds: 0},
	{St_Backclouds: 0},
	{Tilemap: 0},
	{Sprite35: 0},
	{Back1: 0},
	{Sprite36: 0},
	{Sprite10: 0},
	{TX: 0},
	{TY: 0},
	{teleporter: 0},
	{teleporter2: 0},
	{light: 0},
	{firefly: 0},
	{black: 0},
	{Particle_flu: 0},
	{St_Li2: 0},
	{Sprite38: 0},
	{St_Li: 0},
	{countdown: 0},
	{stafe: 0},
	{Horizon: 0},
	{TiledBackground6: 0},
	{Variable1: 0},
	{TiledBackground7: 0},
	{Spawn_platform: 0},
	{Spawn_Lit: 0},
	{c: 0},
	{CHar: 0},
	{CBar: 0},
	{C_base: 0},
	{Sprite4: 0},
	{Dir: 0},
	{Mode: 0},
	{Counter: 0},
	{P_fade: 0},
	{Toyc_p: 0},
	{Particle_flu2: 0},
	{SmurfSelec: 0},
	{Sprite19: 0},
	{PauseSquare: 0},
	{Fade: 0},
	{fade: 0},
	{Touch: 0},
	{Sprite21: 0},
	{Sprite22: 0},
	{xd: 0},
	{Sprite25: 0},
	{ModalBox: 0},
	{Sprite26: 0},
	{Sprite27: 0},
	{TiledBackground8: 0},
	{Sprite28: 0},
	{Sprite29: 0},
	{Sprite32: 0},
	{TiledBackground9: 0},
	{TiledBackground10: 0},
	{Sprite33: 0},
	{Anchor: 0},
	{DragDrop: 0},
	{Button: 0},
	{movecursor: 0},
	{PlatformInfo: 0},
	{ButtonD: 0},
	{ButtonL: 0},
	{ButtonU: 0},
	{ButtonR: 0},
	{Browser: 0},
	{Col: 0},
	{Active: 0},
	{Priority: 0},
	{lockon: 0},
	{solid2: 0},
	{SpriteFont3: 0},
	{NAME: 0},
	{Value: 0},
	{cr_im: 0},
	{Sprite37: 0},
	{Sprite34: 0},
	{Sprite39: 0},
	{psote: 0},
	{Distances: 0},
	{distance: 0},
	{rope: 0},
	{ison: 0},
	{oy: 0},
	{ropecol: 0},
	{Prop: 0},
	{Sprite40: 0},
	{Button2: 0},
	{Sprite41: 0},
	{TiledBackground11: 0},
	{TiledBackground12: 0},
	{Sprite42: 0},
	{Photon: 0},
	{a: 0},
	{chickengodFinalboss: 0},
	{R_icon1: 0},
	{R_icon3: 0},
	{Sprite44: 0},
	{Sprite45: 0},
	{R_icon2: 0},
	{Sprite46: 0},
	{taunt: 0},
	{Rotate: 0},
	{Sprite47: 0},
	{Date: 0},
	{Sprite48: 0},
	{Sprite49: 0},
	{Floppaselec: 0},
	{Floppa_Coin: 0},
	{Set: 0},
	{set2: 0},
	{state: 0},
	{Floppa_side: 0},
	{Sprite50: 0},
	{C1: 0},
	{C2: 0},
	{C3: 0},
	{St_GD: 0},
	{Details_circle: 0},
	{solid3: 0},
	{solid4: 0},
	{St_Mmee: 0},
	{Detail_c: 0},
	{St_minoviawe: 0},
	{Sprite52: 0},
	{Particles3: 0},
	{Sprite53: 0},
	{ojo1: 0},
	{dis: 0},
	{OX: 0},
	{OY: 0},
	{ojo2: 0},
	{St_Oxxo: 0},
	{Sprite51: 0},
	{Sprite54: 0},
	{comments: 0},
	{St_floppa: 0},
	{Points: 0},
	{St_Destroy: 0},
	{TiledBackground13: 0},
	{anim: 0},
	{Details_flop: 0},
	{Details_cube: 0},
	{details_deat: 0},
	{anl: 0},
	{rotate: 0},
	{St_polus: 0},
	{Sprite57: 0},
	{TiledBackground14: 0},
	{Particle_Leaf2: 0},
	{TiledBackground15: 0},
	{Detail_lava: 0},
	{Sprite56: 0},
	{St_windows: 0},
	{Vida: 0},
	{Details_pc: 0},
	{Sprite58: 0},
	{trr: 0},
	{Sprite59: 0},
	{Lo_ima: 0},
	{Reward: 0},
	{Fondo_Logro: 0},
	{Menubutton: 0},
	{Texto_Logro: 0},
	{Son: 0},
	{Type: 0},
	{SECRET: 0},
	{Sprite60: 0},
	{TiledBackground16: 0},
	{Sprite62: 0},
	{Sprite63: 0},
	{ProgressBar: 0},
	{value: 0},
	{ProresBar: 0},
	{RewardID: 0},
	{RewardSTR: 0},
	{Sine2: 0},
	{Sine3: 0},
	{ADD: 0},
	{SOLD_OUT: 0},
	{MobileAdvert: 0},
	{GooglePlay: 0},
	{P_confeti: 0},
	{confeti: 0},
	{Sprite65: 0},
	{starsop: 0},
	{cr_im2: 0},
	{Sprite67: 0},
	{tag: 0},
	{Sprite68: 0},
	{ObjectSelec: 0},
	{wave: 0},
	{FireBallTrail: 0},
	{Troll_cloud: 0},
	{Troll_Face: 0},
	{Troll_Manet: 0},
	{EnergyBeam: 0},
	{Sprite55: 0},
	{Sprite69: 0},
	{backroomlock: 0},
	{Arc_back: 0},
	{SVGPicture: 0},
	{Arc_road2: 0},
	{Arc_road1: 0},
	{Arc_rival: 0},
	{Sprite43: 0},
	{Sprite70: 0},
	{Tilemap2: 0},
	{X1: 0},
	{y1: 0},
	{x2: 0},
	{y2: 0},
	{Target_Prob: 0},
	{Target_Prob2: 0},
	{Target_Prob3: 0},
	{Targetcloud_1: 0},
	{Particle_flu3: 0},
	{Targetcloud_2: 0},
	{Numberarrow: 0},
	{twe: 0},
	{Numberbox: 0},
	{solidRooms: 0},
	{Bluetooth: 0},
	{momos: 0},
	{HP: 0},
	{Boss_body: 0},
	{Boss_body2: 0},
	{Boss_body3: 0},
	{Particles4: 0},
	{xx: 0},
	{xy: 0},
	{wid: 0},
	{Boss_prob1: 0},
	{Price: 0},
	{Reto_medal: 0},
	{Sprite73: 0},
	{Sprite61: 0},
	{Sprite72: 0},
	{SliderBar: 0},
	{Menu_arrow: 0},
	{Blocked: 0},
	{Menu_Color: 0},
	{backSkins: 0},
	{Sprite75: 0},
	{Follow: 0},
	{Crawly_uy: 0},
	{Particles5: 0},
	{Button3: 0},
	{Nyan_Arc: 0},
	{combo: 0},
	{TextInput: 0},
	{bone_p1: 0},
	{Bonep2: 0},
	{Sans_blaster: 0},
	{Sans_blaster2: 0},
	{sans_AM: 0},
	{St_rin: 0},
	{St_rin2: 0},
	{Sprite76: 0},
	{St_rin3: 0},
	{St_rin4: 0},
	{st_fruit: 0},
	{Sprite77: 0},
	{St_rin5: 0},
	{Trofeo: 0},
	{trofeo_2: 0},
	{brillo: 0},
	{brillo2: 0},
	{Sprite78: 0},
	{Nyan_arrow: 0},
	{Particle_Star: 0},
	{Particle_Bubble: 0},
	{Nyan_ball: 0},
	{TYPE: 0},
	{Nyan_marker: 0},
	{Share: 0},
	{FileSystem: 0},
	{FileChooser: 0},
	{Sprite79: 0},
	{Onlinemenu_2: 0},
	{OnlineMenu_Ob1: 0},
	{Sprite81: 0},
	{R_icon4: 0},
	{Numbers: 0},
	{Sprite82: 0},
	{ModeStr: 0},
	{Onlinemenu_3: 0},
	{Sprite84: 0},
	{Booster: 0},
	{TiledBackground17: 0},
	{Sprite64: 0},
	{dm: 0},
	{Burn: 0},
	{HurtZone: 0},
	{Nyan_ob: 0},
	{thunder: 0},
	{triffer: 0},
	{Overlay_mask: 0},
	{Orbit: 0},
	{Sprite80: 0},
	{Particles6: 0},
	{mode: 0},
	{TacNayn: 0},
	{Canceler: 0},
	{St_pvz: 0},
	{NyanCarta: 0},
	{Sprite83: 0},
	{trofeo_list: 0},
	{spooky: 0},
	{TiledBackground18: 0},
	{Hp: 0},
	{type: 0},
	{Zombie: 0},
	{ZombiePart: 0},
	{P: 0},
	{zombiepart2: 0},
	{Tilemap3: 0},
	{TiledBackground19: 0},
	{PvzSun: 0},
	{Video: 0},
	{Sprite85: 0},
	{typw: 0},
	{Pelo_gift: 0},
	{Pelo_select: 0},
	{Particle_quesobo: 0},
	{Pelo_bomb: 0},
	{spookydance: 0},
	{St_hole: 0},
	{item2: 0},
	{Particle_fluone: 0},
	{Particle_fluUp: 0},
	{AdvancedRandom: 0},
	{Laser: 0},
	{Particle_fluUp2: 0},
	{Item_slot: 0},
	{Sprite86: 0},
	{confusofnaf: 0},
	{Sprite87: 0},
	{fnaf_sus: 0},
	{Sprite90: 0},
	{TiledBackground20: 0},
	{fnaf_luz: 0},
	{Pathfinding: 0},
	{fnaf_black: 0},
	{fnaf_litc: 0},
	{fire_particle: 0},
	{Particle_fire: 0},
	{STATE: 0},
	{started: 0},
	{started2: 0},
	{state2: 0},
	{started3: 0},
	{umad_milor: 0},
	{Sprite89: 0},
	{frame: 0},
	{talkin: 0},
	{Umad_cr: 0},
	{Particle_dust: 0},
	{wood: 0},
	{Particle_wood: 0},
	{particle_wood2: 0},
	{blackflash: 0},
	{player_hitbox: 0},
	{Item_explobomb: 0},
	{Particle_dust2: 0},
	{Particle_Star2: 0},
	{Item_Frasco: 0},
	{item_internet: 0},
	{st_milor: 0},
	{St_nave: 0},
	{Train_1: 0},
	{Lay: 0},
	{train_2: 0},
	{st_cañon: 0},
	{Var: 0},
	{var2: 0},
	{"9patch": 0},
	{TextInput2: 0},
	{TiledBackground21: 0},
	{GreenScreen: 0},
	{Sprite92: 0},
	{TiledBackground22: 0},
	{st_faierbol: 0},
	{st_brid: 0},
	{online_back: 0},
	{Onlinebutton: 0},
	{im: 0},
	{online_im: 0},
	{onlinepoint: 0},
	{Online_FL: 0},
	{onlinebj: 0},
	{Sprite93: 0},
	{Sprite94: 0},
	{Walk: 0},
	{Action: 0},
	{PosX: 0},
	{Action2: 0},
	{Quality: 0},
	{pet: 0},
	{petBody: 0},
	{Sprite91: 0},
	{Cabeza: 0},
	{Cara: 0},
	{Cuerpo: 0},
	{Fondo: 0},
	{AVATAR: 0},
	{start: 0},
	{Yx: 0},
	{Avatarmenuslot: 0},
	{TiledBackground23: 0},
	{TiledBackground24: 0},
	{AvatarMenubutton: 0},
	{avatarname: 0},
	{Sprite99: 0},
	{Avatar_1: 0},
	{Avatar_2: 0},
	{Avatar_3: 0},
	{inout: 0},
	{MENU: 0},
	{Avatarmenuitem: 0},
	{trravatar: 0},
	{Avatar_4: 0},
	{TextInput3: 0},
	{roomname: 0},
	{pass: 0},
	{playercount: 0},
	{pin: 0},
	{privateroom: 0},
	{privatebutton: 0},
	{avatarslo: 0},
	{connected: 0},
	{Sprite88: 0},
	{pelor_1: 0},
	{PeloR_im: 0},
	{Sprite95: 0},
	{boss_prob2: 0},
	{bossprob_4: 0},
	{boss_prob4: 0},
	{ojo: 0},
	{ssk_pp: 0},
	{Sprite96: 0},
	{var: 0},
	{XY: 0},
	{XX: 0},
	{bossprob2: 0},
	{Sprite98: 0},
	{Life: 0},
	{minlif: 0},
	{dtroy: 0},
	{bossprob: 0},
	{maxv: 0},
	{boss_health: 0},
	{boss_health2: 0},
	{boss_health3: 0},
	{boss_prob6: 0},
	{boss_prob5: 0},
	{Sprite97: 0},
	{bossprob5: 0},
	{n: 0},
	{bossList: 0},
	{TiledBackground25: 0},
	{bossprob6: 0},
	{size: 0},
	{size2: 0},
	{"9patch2": 0},
	{mira: 0},
	{kaminari: 0},
	{life: 0},
	{PrevVar: 0},
	{blop_boss: 0},
	{wave2: 0},
	{Sprite100: 0},
	{sk: 0},
	{atk: 0},
	{bloplas1: 0},
	{bloplas2: 0},
	{mirror: 0},
	{bloplas3: 0},
	{bloplas4: 0},
	{bloplas5: 0},
	{wave3: 0},
	{blop_saw: 0},
	{blop_ray: 0},
	{TiledBackground26: 0},
	{Sprite101: 0},
	{TiledBackground27: 0},
	{"3DShape3": 0},
	{Sprite102: 0},
	{Boss_body4: 0},
	{cat_explo: 0},
	{catportal: 0},
	{Sprite103: 0},
	{catpinga: 0},
	{Objeto: 0},
	{FileChooser2: 0},
	{Sprite71: 0},
	{tralaSplash: 0},
	{Sprite104: 0},
	{ssss: 0},
	{pisoMasc: 0},
	{Unlock: 0},
	{pet_slot: 0},
	{mascotasBotonTienda: 0},
	{Selected: 0},
	{scrollstart: 0},
	{scrollend: 0},
	{ruleta: 0},
	{posnomas: 0},
	{sdsda: 0},
	{pet_slot2: 0},
	{Scroll: 0},
	{itemshophitvox: 0},
	{itm: 0},
	{itm2: 0},
	{itm3: 0},
	{itm4: 0},
	{itm5: 0},
	{itm6: 0},
	{spd: 0},
	{bigruleta: 0},
	{Sprite106: 0},
	{Ruletaitrm: 0},
	{Sprite74: 0},
	{get: 0},
	{List3: 0},
	{Sprite66: 0},
	{"9patch3": 0},
	{EditorButton: 0},
	{Songlist: 0},
	{EditorScalePin: 0},
	{EditorCheck: 0},
	{EditorEventBlock: 0},
	{EditorPlus: 0},
	{EventList: 0},
	{EditAcc: 0},
	{EditorEventBlock2: 0},
	{EventObjList: 0},
	{EventObjList2: 0},
	{EventFramList: 0},
	{EditorEventErase: 0},
	{SineList: 0},
	{ID3: 0},
	{ID4: 0},
	{Movepoint: 0},
	{MoveLine: 0},
	{EditorPlus2: 0},
	{EditAcc2: 0},
	{EventList2: 0},
	{EditorEventBlock3: 0},
	{EventList3: 0},
	{EditorCheck2: 0},
	{EventFramList2: 0},
	{"99Bg": 0},
	{EditorMenu: 0},
	{EditorMenubutton: 0},
	{EditorMenubutton2: 0},
	{Lopaeditor: 0},
	{Page: 0},
	{StageNext: 0},
	{StageImage2: 0},
	{StageImage3: 0},
	{desctext: 0},
	{desctext3: 0},
	{Sprite20: 0},
	{MovesetView: 0},
	{Ost_Star: 0},
	{Nube_pou: 0},
	{Assist: 0},
	{bossprob3: 0},
	{Caca_pou: 0},
	{Sprite105: 0},
	{Sprite107: 0},
	{Stage_Img4: 0},
	{Stage_gptmon: 0},
	{boss_prob7: 0},
	{stage_space: 0},
	{Sprite108: 0},
	{st_polus_Trr: 0},
	{st_float: 0},
	{menuulock: 0},
	{item_shield: 0},
	{item_ball: 0},
	{ob_luckyblock: 0},
	{grasamenu: 0},
	{st_ai: 0},
	{TiledBackground28: 0},
	{JSON: 0},
	{Family1: 0},
	{Physics2: 0},
	{roes: 0},
	{Family2: 0},
	{E_buttons: 0},
	{Editor_Obj: 0},
	{Family3: 0},
	{Family4: 0},
	{SFX: 0},
	{BGM: 0},
	{Variable2: 0},
	{Text: 0},
	{timer: 0},
	{C4: 0},
	{MenuSelected: 0},
	{K_KEYCODE: 0},
	{KEY_PAUSE: 0},
	{KEY_UP: 0},
	{KEY_DOWN: 0},
	{KEY_RIGHT: 0},
	{KEY_LEFT: 0},
	{KEY_Jump: 0},
	{KEY_T: 0},
	{KEY_D: 0},
	{KEY_C: 0},
	{KEY_B: 0},
	{KEY_A: 0},
	{KEY_PAUSE2: 0},
	{KEY_UP2: 0},
	{KEY_DOWN2: 0},
	{KEY_RIGHT2: 0},
	{KEY_LEFT2: 0},
	{KEY_Jump2: 0},
	{KEY_T2: 0},
	{KEY_D2: 0},
	{KEY_C2: 0},
	{KEY_B2: 0},
	{KEY_A2: 0},
	{KEY_PAUSE3: 0},
	{KEY_UP3: 0},
	{KEY_DOWN3: 0},
	{KEY_RIGHT3: 0},
	{KEY_LEFT3: 0},
	{KEY_Jump3: 0},
	{KEY_T3: 0},
	{KEY_D3: 0},
	{KEY_C3: 0},
	{KEY_B3: 0},
	{KEY_A3: 0},
	{KEY_PAUSE4: 0},
	{KEY_UP4: 0},
	{KEY_DOWN4: 0},
	{KEY_RIGHT4: 0},
	{KEY_LEFT4: 0},
	{KEY_Jump4: 0},
	{KEY_T4: 0},
	{KEY_D4: 0},
	{KEY_C4: 0},
	{KEY_B4: 0},
	{KEY_A4: 0},
	{CHAR1: 0},
	{CHAR2: 0},
	{CHAR3: 0},
	{CHAR4: 0},
	{COLOR1: 0},
	{COLOR2: 0},
	{COLOR3: 0},
	{COLOR4: 0},
	{cpu1: 0},
	{cpu2: 0},
	{cpu3: 0},
	{cpu4: 0},
	{L1: 0},
	{L2: 0},
	{L3: 0},
	{L4: 0},
	{TICKETS: 0},
	{PET1: 0},
	{PET2: 0},
	{PET3: 0},
	{PET4: 0},
	{editin: 0},
	{editin2: 0},
	{editin3: 0},
	{MedalValue: 0},
	{Char: 0},
	{Cselect: 0},
	{Ch: 0},
	{GamepadCount: 0},
	{LDM: 0},
	{IH: 0},
	{Rumble: 0},
	{Vbutt: 0},
	{Clock: 0},
	{clock2: 0},
	{Stocks: 0},
	{TimeSet: 0},
	{INITIALHP: 0},
	{StockSet: 0},
	{Hazards: 0},
	{StagePage: 0},
	{Spooky: 0},
	{Version: 0},
	{Actor2: 0},
	{OnlineTimer: 0},
	{myplayer: 0},
	{mycolor: 0},
	{OnlineMode: 0},
	{Variable2a: 0},
	{EnemyV: 0},
	{x: 0},
	{STAGE: 0},
	{Playcount: 0},
	{Gamemode: 0},
	{Ready: 0},
	{pingascount: 0},
	{pollas: 0},
	{P1Combo: 0},
	{P1Combo2: 0},
	{P1Combo3: 0},
	{P1Combo4: 0},
	{Camera: 0},
	{Clima: 0},
	{Countdown: 0},
	{Light: 0},
	{ControlsVisible: 0},
	{Latencia: 0},
	{CASH: 0},
	{var3: 0},
	{var4: 0},
	{MenuOST: 0},
	{son: 0},
	{Checking: 0},
	{RUNTIME: 0},
	{dets: 0},
	{tings: 0},
	{nc: 0},
	{ID_LOGRO: 0},
	{MONEY: 0},
	{Dailytime: 0},
	{Rewards: 0},
	{ST: 0},
	{MenuS: 0},
	{Charpl: 0},
	{IDextra: 0},
	{PRICEextra: 0},
	{menus: 0},
	{menus2: 0},
	{menus3: 0},
	{BotNumber: 0},
	{SET: 0},
	{PLayer: 0},
	{Chr: 0},
	{posx: 0},
	{posy: 0},
	{ANG: 0},
	{Ronda: 0},
	{P1Stocks: 0},
	{Cash2: 0},
	{ArcadePoints: 0},
	{IFstock: 0},
	{Tarjets: 0},
	{posno: 0},
	{Recordtime: 0},
	{Tunder: 0},
	{Tacnayn: 0},
	{Pattern: 0},
	{Pattern2: 0},
	{Diamonds: 0},
	{Crowns: 0},
	{Region: 0},
	{VIDEOID: 0},
	{VIDEOFuente: 0},
	{OBspawntime: 0},
	{locx: 0},
	{locy: 0},
	{speedo: 0},
	{an1: 0},
	{vy1: 0},
	{vx1: 0},
	{J: 0},
	{GLOBALTIME: 0},
	{ActiveTime: 0},
	{MaiState: 0},
	{OnlineGameMode: 0},
	{ModePause: 0},
	{MovesetVar: 0},
	{trainid: 0},
	{pl: 0},
	{rivalavatar: 0},
	{UserName: 0},
	{option: 0},
	{Sombrero: 0},
	{caracters: 0},
	{ROOMCODE: 0},
	{code2: 0},
	{code: 0},
	{CASH3: 0},
	{GameValue: 0},
	{CL1: 0},
	{CL2: 0},
	{CL3: 0},
	{TrowSpeed: 0},
	{randomVar: 0},
	{prob: 0},
	{Ojillo: 0},
	{Ojillo2: 0},
	{UID: 0},
	{TimerNumber: 0},
	{waittimer: 0},
	{Signal: 0},
	{Val1: 0},
	{Val2: 0},
	{Val3: 0},
	{Condition: 0},
	{Val4: 0},
	{Val5: 0},
	{Val6: 0},
	{ConditionActived: 0},
	{loop: 0},
	{peloreto2: 0},
	{pelovidas: 0},
	{Camera_Velocity: 0},
	{ActualFrame: 0},
	{ActuaLayer: 0},
	{E_ObjCount: 0},
	{CanEdit: 0},
	{Cargar: 0},
	{temp: 0},
	{ChangingLayer: 0},
	{tSpeed: 0},
	{tangle: 0},
	{EditorValue: 0},
	{MaxEvents: 0},
	{CurrentEvent: 0},
	{CurEvent: 0},
	{CurEvent2: 0},
	{CurEvent3: 0},
	{curmov: 0},
	{lastcreatedblock: 0},
	{miBase64: 0},
	{miCompressed: 0},
	{miJSON: 0},
	{ChallengerCHR: 0},
	{PetRevenew: 0},
	{PetRevenew2: 0}
];

self.InstanceType = {
	Arcaderoad: class extends self.IArrayInstance {},
	colors: class extends self.IArrayInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	Keys: class extends self.IArrayInstance {},
	KEYS2: class extends self.IArrayInstance {},
	List: class extends self.IListInstance {},
	List2: class extends self.IListInstance {},
	List_Museom: class extends self.IListInstance {},
	List_OST: class extends self.IListInstance {},
	Logros: class extends self.IArrayInstance {},
	Logros2: class extends self.IArrayInstance {},
	MUSEOM: class extends self.IArrayInstance {},
	Names: class extends self.IArrayInstance {},
	Neims: class extends self.IArrayInstance {},
	P_Char: class extends self.IDictionaryInstance {},
	P_museo: class extends self.IDictionaryInstance {},
	P_OnlyforOSTAchiev: class extends self.IDictionaryInstance {},
	P_Ost: class extends self.IDictionaryInstance {},
	P_Stages: class extends self.IDictionaryInstance {},
	Stadistics: class extends self.IArrayInstance {},
	Stats: class extends self.IArrayInstance {},
	Upk: class extends self.IArrayInstance {},
	ArcadeArray: class extends self.IArrayInstance {},
	ArcadeNumbers: class extends self.IDictionaryInstance {},
	Colorsget: class extends self.IDictionaryInstance {},
	codes: class extends self.IDictionaryInstance {},
	Online_Levels: class extends self.IArrayInstance {},
	Online_Data: class extends self.IDictionaryInstance {},
	ITEMS: class extends self.IArrayInstance {},
	itemsActivated: class extends self.IArrayInstance {},
	Avatararry: class extends self.IArrayInstance {},
	Avatarkeys: class extends self.IDictionaryInstance {},
	LogrosRecompensas: class extends self.IDictionaryInstance {},
	peloreto: class extends self.IArrayInstance {},
	E_array2: class extends self.IArrayInstance {},
	Moveset: class extends self.IArrayInstance {},
	ColArcLogros: class extends self.IDictionaryInstance {},
	grasadial: class extends self.IArrayInstance {},
	E_9patch: class extends self.IWorldInstance {},
	E_Arrow: class extends self.ISpriteInstance {},
	E_Bg: class extends self.ITiledBackgroundInstance {},
	E_camera: class extends self.ISpriteInstance {},
	E_obj: class extends self.ISpriteInstance {},
	Less_Height: class extends self.ISpriteInstance {},
	Less_size: class extends self.ISpriteInstance {},
	Less_Witdh: class extends self.ISpriteInstance {},
	Plus_Height: class extends self.ISpriteInstance {},
	Plus_size: class extends self.ISpriteInstance {},
	Plus_Witdh: class extends self.ISpriteInstance {},
	Rotate_Left: class extends self.ISpriteInstance {},
	Rotate_Right: class extends self.ISpriteInstance {},
	SaveButton: class extends self.ISpriteInstance {},
	SaveButton2: class extends self.ISpriteInstance {},
	SaveButton3: class extends self.ISpriteInstance {},
	Framearray: class extends self.IArrayInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	E_array: class extends self.IArrayInstance {},
	Delete: class extends self.ISpriteInstance {},
	Clone: class extends self.ISpriteInstance {},
	flip: class extends self.ISpriteInstance {},
	Mirror: class extends self.ISpriteInstance {},
	EdgeSpawner: class extends self.ISpriteInstance {},
	EditorColor: class extends self.ISpriteInstance {},
	EditorInput: class extends self.ITextInputInstance {},
	EditorSlC1: class extends self.ISliderBarInstance {},
	EditorSlC2: class extends self.ISliderBarInstance {},
	EditorSlC3: class extends self.ISliderBarInstance {},
	EditEditor: class extends self.ISpriteInstance {},
	EditorInput2: class extends self.ITextInputInstance {},
	EventArray: class extends self.IArrayInstance {},
	Eventinput: class extends self.ITextInputInstance {},
	Eventinput2: class extends self.ITextInputInstance {},
	EDITOR: class extends self.IDictionaryInstance {},
	ChangeLayer: class extends self.ISpriteInstance {},
	ola3: class extends self.ISpriteFontInstance {},
	Mascotas: class extends self.IDictionaryInstance {},
	pets: class extends self.IArrayInstance {},
	player: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	solid: class extends self.ISpriteInstance {},
	mask: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	hitbox: class extends self.ISpriteInstance {},
	player2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Men_Button: class extends self.ISpriteInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	Gamepad: class extends self.IInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	trans: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Charslot: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	TOWER: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Hand: class extends self.ISpriteInstance {},
	Char_Selector: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	charescreen: class extends self.ISpriteInstance {},
	CAMPRINCIPAL: class extends self.ISpriteInstance {},
	Camsec1: class extends self.ISpriteInstance {},
	Camsec2: class extends self.ISpriteInstance {},
	CAMPRINCIPAL2: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Saved: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	OnOff: class extends self.ISpriteInstance {},
	Camsec3: class extends self.ISpriteInstance {},
	Camsec4: class extends self.ISpriteInstance {},
	particulas: class extends self.ISpriteInstance {},
	flash: class extends self.ISpriteInstance {},
	Ud_line: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	ud_rombo: class extends self.ISpriteInstance {},
	icon: class extends self.ISpriteInstance {},
	shield: class extends self.ISpriteInstance {},
	edge: class extends self.ISpriteInstance {},
	stockhud: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	grab: class extends self.ISpriteInstance {},
	Sprite23: class extends self.ISpriteInstance {},
	Sprite24: class extends self.ISpriteInstance {},
	FlowchartController: class extends self.IInstance {},
	spawner: class extends self.ISpriteInstance {},
	Multiplayer: class extends self.IInstance {},
	proyectil: class extends self.ISpriteInstance {},
	Pointer: class extends self.ISpriteInstance {},
	Percentaje: class extends self.ISpriteFontInstance {},
	P1mark: class extends self.ISpriteInstance {},
	P2mark: class extends self.ISpriteInstance {},
	P3mark: class extends self.ISpriteInstance {},
	P4mark: class extends self.ISpriteInstance {},
	deatheffect: class extends self.ISpriteInstance {},
	deathzone: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	St_BackPlanes: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	cloud2: class extends self.ISpriteInstance {},
	titlecard: class extends self.ISpriteInstance {},
	St_Lit3: class extends self.ISpriteInstance {},
	Men_Back: class extends self.ISpriteInstance {},
	StageImage: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	_3DShape2: class extends self.I3DShapeInstance {},
	StageView: class extends self.ISpriteInstance {},
	Plane: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	Particles2: class extends self.IParticlesInstance {},
	Particles: class extends self.IParticlesInstance {},
	forest: class extends self.ISpriteInstance {},
	Mushrooms: class extends self.ISpriteInstance {},
	St_Backtrees: class extends self.ISpriteInstance {},
	Sprite30: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite31: class extends self.ISpriteInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	T78B: class extends self.ISpriteInstance {},
	Particle_Leaf: class extends self.IParticlesInstance {},
	raindrop: class extends self.ISpriteInstance {},
	Particle_rain: class extends self.IParticlesInstance {},
	St_ouse: class extends self.ISpriteInstance {},
	St_BackBuilds: class extends self.ISpriteInstance {},
	St_Backclouds: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite35: class extends self.ISpriteInstance {},
	Back1: class extends self.ISpriteInstance {},
	Sprite36: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	teleporter: class extends self.ISpriteInstance {},
	teleporter2: class extends self.ISpriteInstance {},
	light: class extends self.ISpriteInstance {},
	firefly: class extends self.ISpriteInstance {},
	black: class extends self.ISpriteInstance {},
	Particle_flu: class extends self.IParticlesInstance {},
	St_Li2: class extends self.ISpriteInstance {},
	Sprite38: class extends self.ISpriteInstance {},
	St_Li: class extends self.ISpriteInstance {},
	countdown: class extends self.ISpriteInstance {},
	stafe: class extends self.ISpriteInstance {},
	Horizon: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	TiledBackground7: class extends self.ITiledBackgroundInstance {},
	Spawn_platform: class extends self.ISpriteInstance {},
	Spawn_Lit: class extends self.ISpriteInstance {},
	CBar: class extends self.ISpriteInstance {},
	C_base: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Counter: class extends self.ISpriteInstance {},
	P_fade: class extends self.ISpriteInstance {},
	Toyc_p: class extends self.ISpriteInstance {},
	Particle_flu2: class extends self.IParticlesInstance {},
	SmurfSelec: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	PauseSquare: class extends self.ISpriteInstance {},
	fade: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Sprite21: class extends self.ISpriteInstance {},
	Sprite22: class extends self.ISpriteInstance {},
	Sprite25: class extends self.ISpriteInstance {},
	ModalBox: class extends self.IWorldInstance {},
	Sprite26: class extends self.ISpriteInstance {},
	Sprite27: class extends self.ISpriteInstance {},
	TiledBackground8: class extends self.ITiledBackgroundInstance {},
	Sprite28: class extends self.ISpriteInstance {},
	Sprite29: class extends self.ISpriteInstance {},
	Sprite32: class extends self.ISpriteInstance {},
	TiledBackground9: class extends self.ITiledBackgroundInstance {},
	TiledBackground10: class extends self.ITiledBackgroundInstance {},
	Sprite33: class extends self.ISpriteInstance {},
	Button: class extends self.ISpriteInstance {},
	movecursor: class extends self.ISpriteInstance {},
	PlatformInfo: class extends self.IInstance {},
	ButtonD: class extends self.ISpriteInstance {},
	ButtonL: class extends self.ISpriteInstance {},
	ButtonU: class extends self.ISpriteInstance {},
	ButtonR: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Col: class extends self.ISpriteInstance {},
	lockon: class extends self.ISpriteInstance {},
	solid2: class extends self.ISpriteInstance {},
	SpriteFont3: class extends self.ISpriteFontInstance {},
	cr_im: class extends self.ISpriteInstance {},
	Sprite37: class extends self.ISpriteInstance {},
	Sprite34: class extends self.ISpriteInstance {},
	Sprite39: class extends self.ISpriteInstance {},
	psote: class extends self.ISpriteInstance {},
	rope: class extends self.ISpriteInstance {},
	ropecol: class extends self.ISpriteInstance {},
	Prop: class extends self.ISpriteInstance {},
	Sprite40: class extends self.ISpriteInstance {},
	Button2: class extends self.ISpriteInstance {},
	Sprite41: class extends self.ISpriteInstance {},
	TiledBackground11: class extends self.ITiledBackgroundInstance {},
	TiledBackground12: class extends self.ITiledBackgroundInstance {},
	Sprite42: class extends self.ISpriteInstance {},
	Photon: class extends self.IInstance {},
	chickengodFinalboss: class extends self.ISpriteInstance {},
	R_icon1: class extends self.ISpriteInstance {},
	R_icon3: class extends self.ISpriteInstance {},
	Sprite44: class extends self.ISpriteInstance {},
	Sprite45: class extends self.ISpriteInstance {},
	R_icon2: class extends self.ISpriteInstance {},
	Sprite46: class extends self.ISpriteInstance {},
	taunt: class extends self.ISpriteInstance {},
	Sprite47: class extends self.ISpriteInstance {},
	Date: class extends self.IInstance {},
	Sprite48: class extends self.ISpriteInstance {},
	Sprite49: class extends self.ISpriteInstance {},
	Floppaselec: class extends self.ISpriteInstance {},
	Floppa_Coin: class extends self.ISpriteInstance {},
	Floppa_side: class extends self.ISpriteInstance {},
	Sprite50: class extends self.ISpriteInstance {},
	St_GD: class extends self.ISpriteInstance {},
	Details_circle: class extends self.ISpriteInstance {},
	solid3: class extends self.ISpriteInstance {},
	solid4: class extends self.ISpriteInstance {},
	St_Mmee: class extends self.ISpriteInstance {},
	Detail_c: class extends self.ISpriteInstance {},
	St_minoviawe: class extends self.ISpriteInstance {},
	Sprite52: class extends self.ISpriteInstance {},
	Particles3: class extends self.IParticlesInstance {},
	Sprite53: class extends self.ISpriteInstance {},
	ojo1: class extends self.ISpriteInstance {},
	ojo2: class extends self.ISpriteInstance {},
	St_Oxxo: class extends self.ISpriteInstance {},
	Sprite51: class extends self.ISpriteInstance {},
	Sprite54: class extends self.ISpriteInstance {},
	comments: class extends self.ISpriteInstance {},
	St_floppa: class extends self.ISpriteInstance {},
	St_Destroy: class extends self.ISpriteInstance {},
	TiledBackground13: class extends self.ITiledBackgroundInstance {},
	Details_flop: class extends self.ISpriteInstance {},
	Details_cube: class extends self.ISpriteInstance {},
	details_deat: class extends self.ISpriteInstance {},
	St_polus: class extends self.ISpriteInstance {},
	Sprite57: class extends self.ISpriteInstance {},
	TiledBackground14: class extends self.ITiledBackgroundInstance {},
	Particle_Leaf2: class extends self.IParticlesInstance {},
	TiledBackground15: class extends self.ITiledBackgroundInstance {},
	Detail_lava: class extends self.ISpriteInstance {},
	Sprite56: class extends self.ISpriteInstance {},
	St_windows: class extends self.ISpriteInstance {},
	Details_pc: class extends self.ISpriteInstance {},
	Sprite58: class extends self.ISpriteInstance {},
	trr: class extends self.ISpriteInstance {},
	Sprite59: class extends self.ISpriteInstance {},
	Lo_ima: class extends self.ISpriteInstance {},
	Fondo_Logro: class extends self.ISpriteInstance {},
	Menubutton: class extends self.ISpriteInstance {},
	Texto_Logro: class extends self.ISpriteFontInstance {},
	Sprite60: class extends self.ISpriteInstance {},
	TiledBackground16: class extends self.ITiledBackgroundInstance {},
	Sprite62: class extends self.ISpriteInstance {},
	Sprite63: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	ProresBar: class extends self.ISpriteInstance {},
	ADD: class extends self.ISpriteInstance {},
	SOLD_OUT: class extends self.ISpriteInstance {},
	MobileAdvert: class extends self.IInstance {},
	GooglePlay: class extends self.IInstance {},
	P_confeti: class extends self.IParticlesInstance {},
	confeti: class extends self.ISpriteInstance {},
	Sprite65: class extends self.ISpriteInstance {},
	starsop: class extends self.ISpriteInstance {},
	cr_im2: class extends self.ISpriteInstance {},
	Sprite67: class extends self.ISpriteInstance {},
	tag: class extends self.ISpriteInstance {},
	Sprite68: class extends self.ISpriteInstance {},
	ObjectSelec: class extends self.ISpriteInstance {},
	wave: class extends self.ISpriteInstance {},
	FireBallTrail: class extends self.ISpriteInstance {},
	Troll_cloud: class extends self.ISpriteInstance {},
	Troll_Face: class extends self.ISpriteInstance {},
	Troll_Manet: class extends self.ISpriteInstance {},
	EnergyBeam: class extends self.ITiledBackgroundInstance {},
	Sprite55: class extends self.ISpriteInstance {},
	Sprite69: class extends self.ISpriteInstance {},
	backroomlock: class extends self.ISpriteInstance {},
	Arc_back: class extends self.ISpriteInstance {},
	SVGPicture: class extends self.ISVGPictureInstance {},
	Arc_road2: class extends self.ISpriteInstance {},
	Arc_road1: class extends self.ISpriteInstance {},
	Arc_rival: class extends self.ISpriteInstance {},
	Sprite43: class extends self.ISpriteInstance {},
	Sprite70: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Target_Prob: class extends self.ISpriteInstance {},
	Target_Prob2: class extends self.ISpriteInstance {},
	Target_Prob3: class extends self.ISpriteInstance {},
	Targetcloud_1: class extends self.ITiledBackgroundInstance {},
	Particle_flu3: class extends self.IParticlesInstance {},
	Targetcloud_2: class extends self.ISpriteInstance {},
	Numberarrow: class extends self.ISpriteInstance {},
	Numberbox: class extends self.ISpriteInstance {},
	solidRooms: class extends self.ISpriteInstance {},
	Bluetooth: class extends self.IInstance {},
	momos: class extends self.ISpriteInstance {},
	Boss_body: class extends self.ISpriteInstance {},
	Boss_body2: class extends self.ISpriteInstance {},
	Boss_body3: class extends self.ISpriteInstance {},
	Particles4: class extends self.IParticlesInstance {},
	Boss_prob1: class extends self.ISpriteInstance {},
	Reto_medal: class extends self.ISpriteInstance {},
	Sprite73: class extends self.ISpriteInstance {},
	Sprite61: class extends self.ISpriteInstance {},
	Sprite72: class extends self.ISpriteInstance {},
	SliderBar: class extends self.ISliderBarInstance {},
	Menu_arrow: class extends self.ISpriteInstance {},
	Menu_Color: class extends self.ISpriteInstance {},
	backSkins: class extends self.ISpriteInstance {},
	Sprite75: class extends self.ISpriteInstance {},
	Crawly_uy: class extends self.ISpriteInstance {},
	Particles5: class extends self.IParticlesInstance {},
	Button3: class extends self.IButtonInstance {},
	Nyan_Arc: class extends self.ISpriteInstance {},
	combo: class extends self.ISpriteInstance {},
	TextInput: class extends self.ITextInputInstance {},
	bone_p1: class extends self.ISpriteInstance {},
	Bonep2: class extends self.ISpriteInstance {},
	Sans_blaster: class extends self.ISpriteInstance {},
	Sans_blaster2: class extends self.ISpriteInstance {},
	sans_AM: class extends self.ISpriteInstance {},
	St_rin: class extends self.ISpriteInstance {},
	St_rin2: class extends self.ISpriteInstance {},
	Sprite76: class extends self.ISpriteInstance {},
	St_rin3: class extends self.ISpriteInstance {},
	St_rin4: class extends self.ISpriteInstance {},
	st_fruit: class extends self.ISpriteInstance {},
	Sprite77: class extends self.ISpriteInstance {},
	St_rin5: class extends self.ITiledBackgroundInstance {},
	Trofeo: class extends self.ISpriteInstance {},
	trofeo_2: class extends self.ISpriteInstance {},
	brillo: class extends self.ISpriteInstance {},
	brillo2: class extends self.ITiledBackgroundInstance {},
	Sprite78: class extends self.ISpriteInstance {},
	Nyan_arrow: class extends self.ISpriteInstance {},
	Particle_Star: class extends self.IParticlesInstance {},
	Particle_Bubble: class extends self.IParticlesInstance {},
	Nyan_ball: class extends self.ISpriteInstance {},
	Nyan_marker: class extends self.ISpriteInstance {},
	Share: class extends self.IInstance {},
	FileSystem: class extends self.IInstance {},
	FileChooser: class extends self.IFileChooserInstance {},
	Sprite79: class extends self.ISpriteInstance {},
	Onlinemenu_2: class extends self.ISpriteInstance {},
	OnlineMenu_Ob1: class extends self.ISpriteInstance {},
	Sprite81: class extends self.ISpriteInstance {},
	R_icon4: class extends self.ISpriteInstance {},
	Numbers: class extends self.ISpriteFontInstance {},
	Sprite82: class extends self.ISpriteInstance {},
	Onlinemenu_3: class extends self.ISpriteInstance {},
	Sprite84: class extends self.ISpriteInstance {},
	Booster: class extends self.ISpriteInstance {},
	TiledBackground17: class extends self.ITiledBackgroundInstance {},
	Sprite64: class extends self.ISpriteInstance {},
	HurtZone: class extends self.ISpriteInstance {},
	Nyan_ob: class extends self.ISpriteInstance {},
	thunder: class extends self.ISpriteInstance {},
	triffer: class extends self.ISpriteInstance {},
	Overlay_mask: class extends self.ISpriteInstance {},
	Sprite80: class extends self.ISpriteInstance {},
	Particles6: class extends self.IParticlesInstance {},
	TacNayn: class extends self.ISpriteInstance {},
	Canceler: class extends self.ISpriteInstance {},
	St_pvz: class extends self.ISpriteInstance {},
	NyanCarta: class extends self.ISpriteInstance {},
	Sprite83: class extends self.ISpriteInstance {},
	trofeo_list: class extends self.IListInstance {},
	spooky: class extends self.ISpriteInstance {},
	TiledBackground18: class extends self.ITiledBackgroundInstance {},
	Zombie: class extends self.ISpriteInstance {},
	ZombiePart: class extends self.ISpriteInstance {},
	zombiepart2: class extends self.ISpriteInstance {},
	Tilemap3: class extends self.ITilemapInstance {},
	TiledBackground19: class extends self.ITiledBackgroundInstance {},
	PvzSun: class extends self.ISpriteInstance {},
	Video: class extends self.IWorldInstance {},
	Sprite85: class extends self.ISpriteInstance {},
	Pelo_gift: class extends self.ISpriteInstance {},
	Pelo_select: class extends self.ISpriteInstance {},
	Particle_quesobo: class extends self.IParticlesInstance {},
	Pelo_bomb: class extends self.ISpriteInstance {},
	spookydance: class extends self.ISpriteInstance {},
	St_hole: class extends self.ISpriteInstance {},
	item: class extends self.ISpriteInstance {},
	item2: class extends self.ISpriteInstance {},
	Particle_fluone: class extends self.IParticlesInstance {},
	Particle_fluUp: class extends self.IParticlesInstance {},
	AdvancedRandom: class extends self.IInstance {},
	Laser: class extends self.ISpriteInstance {},
	Particle_fluUp2: class extends self.IParticlesInstance {},
	Item_slot: class extends self.ISpriteInstance {},
	Sprite86: class extends self.ISpriteInstance {},
	confusofnaf: class extends self.ISpriteInstance {},
	Sprite87: class extends self.ISpriteInstance {},
	fnaf_sus: class extends self.ISpriteInstance {},
	Sprite90: class extends self.ISpriteInstance {},
	TiledBackground20: class extends self.ITiledBackgroundInstance {},
	fnaf_luz: class extends self.ISpriteInstance {},
	fnaf_black: class extends self.ISpriteInstance {},
	fnaf_litc: class extends self.ISpriteInstance {},
	fire_particle: class extends self.ISpriteInstance {},
	Particle_fire: class extends self.IParticlesInstance {},
	umad_milor: class extends self.ISpriteInstance {},
	Sprite89: class extends self.ISpriteInstance {},
	Umad_cr: class extends self.ISpriteInstance {},
	Particle_dust: class extends self.IParticlesInstance {},
	wood: class extends self.ISpriteInstance {},
	Particle_wood: class extends self.IParticlesInstance {},
	particle_wood2: class extends self.IParticlesInstance {},
	blackflash: class extends self.ISpriteInstance {},
	player_hitbox: class extends self.ISpriteInstance {},
	Item_explobomb: class extends self.ISpriteInstance {},
	Particle_dust2: class extends self.IParticlesInstance {},
	Particle_Star2: class extends self.IParticlesInstance {},
	Item_Frasco: class extends self.ISpriteInstance {},
	item_internet: class extends self.ISpriteInstance {},
	st_milor: class extends self.ISpriteInstance {},
	St_nave: class extends self.ISpriteInstance {},
	Train_1: class extends self.ISpriteInstance {},
	train_2: class extends self.ISpriteInstance {},
	st_cañon: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	TextInput2: class extends self.ITextInputInstance {},
	TiledBackground21: class extends self.ITiledBackgroundInstance {},
	GreenScreen: class extends self.ISpriteInstance {},
	Sprite92: class extends self.ISpriteInstance {},
	TiledBackground22: class extends self.ITiledBackgroundInstance {},
	st_faierbol: class extends self.ISpriteInstance {},
	st_brid: class extends self.ISpriteInstance {},
	online_back: class extends self.ISpriteInstance {},
	Onlinebutton: class extends self.ISpriteInstance {},
	online_im: class extends self.ISpriteInstance {},
	onlinepoint: class extends self.ISpriteInstance {},
	Online_FL: class extends self.ISpriteInstance {},
	onlinebj: class extends self.ISpriteInstance {},
	Sprite93: class extends self.ISpriteInstance {},
	Sprite94: class extends self.ISpriteInstance {},
	pet: class extends self.ISpriteInstance {},
	petBody: class extends self.ISpriteInstance {},
	Sprite91: class extends self.ISpriteInstance {},
	AVATAR: class extends self.ISpriteInstance {},
	Avatarmenuslot: class extends self.ISpriteInstance {},
	TiledBackground23: class extends self.ITiledBackgroundInstance {},
	TiledBackground24: class extends self.ITiledBackgroundInstance {},
	AvatarMenubutton: class extends self.ISpriteInstance {},
	avatarname: class extends self.ISpriteInstance {},
	Sprite99: class extends self.ISpriteInstance {},
	Avatar_1: class extends self.ISpriteInstance {},
	Avatar_2: class extends self.ISpriteInstance {},
	Avatar_3: class extends self.ISpriteInstance {},
	inout: class extends self.ISpriteInstance {},
	Avatarmenuitem: class extends self.ISpriteInstance {},
	trravatar: class extends self.ISpriteInstance {},
	Avatar_4: class extends self.ISpriteInstance {},
	TextInput3: class extends self.ITextInputInstance {},
	privateroom: class extends self.ISpriteInstance {},
	privatebutton: class extends self.ISpriteInstance {},
	avatarslo: class extends self.ISpriteInstance {},
	connected: class extends self.ISpriteInstance {},
	Sprite88: class extends self.ISpriteInstance {},
	pelor_1: class extends self.ISpriteInstance {},
	PeloR_im: class extends self.ISpriteInstance {},
	Sprite95: class extends self.ISpriteInstance {},
	boss_prob2: class extends self.ISpriteInstance {},
	bossprob_4: class extends self.ISpriteInstance {},
	boss_prob4: class extends self.ISpriteInstance {},
	ojo: class extends self.ISpriteInstance {},
	ssk_pp: class extends self.ISpriteInstance {},
	Sprite96: class extends self.ISpriteInstance {},
	bossprob2: class extends self.ISpriteInstance {},
	Sprite98: class extends self.ISpriteInstance {},
	bossprob: class extends self.ISpriteInstance {},
	boss_health: class extends self.ISpriteInstance {},
	boss_health2: class extends self.ISpriteInstance {},
	boss_health3: class extends self.ISpriteInstance {},
	boss_prob6: class extends self.ISpriteInstance {},
	boss_prob5: class extends self.ISpriteInstance {},
	Sprite97: class extends self.ISpriteInstance {},
	bossprob5: class extends self.ISpriteInstance {},
	bossList: class extends self.IListInstance {},
	TiledBackground25: class extends self.ITiledBackgroundInstance {},
	bossprob6: class extends self.ISpriteInstance {},
	_9patch2: class extends self.IWorldInstance {},
	mira: class extends self.ISpriteInstance {},
	kaminari: class extends self.ISpriteInstance {},
	blop_boss: class extends self.ISpriteInstance {},
	wave2: class extends self.ISpriteInstance {},
	Sprite100: class extends self.ISpriteInstance {},
	bloplas1: class extends self.ITiledBackgroundInstance {},
	bloplas2: class extends self.ISpriteInstance {},
	bloplas3: class extends self.ISpriteInstance {},
	bloplas4: class extends self.ISpriteInstance {},
	bloplas5: class extends self.ISpriteInstance {},
	wave3: class extends self.ISpriteInstance {},
	blop_saw: class extends self.ISpriteInstance {},
	blop_ray: class extends self.ISpriteInstance {},
	TiledBackground26: class extends self.ITiledBackgroundInstance {},
	Sprite101: class extends self.ISpriteInstance {},
	TiledBackground27: class extends self.ITiledBackgroundInstance {},
	_3DShape3: class extends self.I3DShapeInstance {},
	Sprite102: class extends self.ISpriteInstance {},
	Boss_body4: class extends self.ISpriteInstance {},
	cat_explo: class extends self.ISpriteInstance {},
	catportal: class extends self.ISpriteInstance {},
	Sprite103: class extends self.ISpriteInstance {},
	catpinga: class extends self.ISpriteInstance {},
	Objeto: class extends self.ISpriteInstance {},
	FileChooser2: class extends self.IFileChooserInstance {},
	Sprite71: class extends self.ISpriteInstance {},
	tralaSplash: class extends self.ISpriteInstance {},
	Sprite104: class extends self.ISpriteInstance {},
	ssss: class extends self.ISpriteInstance {},
	pisoMasc: class extends self.ISpriteInstance {},
	pet_slot: class extends self.ISpriteInstance {},
	mascotasBotonTienda: class extends self.ISpriteInstance {},
	ruleta: class extends self.ISpriteInstance {},
	posnomas: class extends self.ISpriteInstance {},
	sdsda: class extends self.ISpriteInstance {},
	pet_slot2: class extends self.ISpriteInstance {},
	itemshophitvox: class extends self.ISpriteInstance {},
	bigruleta: class extends self.ISpriteInstance {},
	Sprite106: class extends self.ISpriteInstance {},
	Ruletaitrm: class extends self.ISpriteInstance {},
	Sprite74: class extends self.ISpriteInstance {},
	List3: class extends self.IListInstance {},
	Sprite66: class extends self.ISpriteInstance {},
	_9patch3: class extends self.IWorldInstance {},
	EditorButton: class extends self.ISpriteInstance {},
	Songlist: class extends self.IListInstance {},
	EditorScalePin: class extends self.ISpriteInstance {},
	EditorCheck: class extends self.ISpriteInstance {},
	EditorEventBlock: class extends self.ISpriteInstance {},
	EditorPlus: class extends self.ISpriteInstance {},
	EventList: class extends self.IListInstance {},
	EditAcc: class extends self.ISpriteInstance {},
	EditorEventBlock2: class extends self.ISpriteInstance {},
	EventObjList: class extends self.IListInstance {},
	EventObjList2: class extends self.IListInstance {},
	EventFramList: class extends self.IListInstance {},
	EditorEventErase: class extends self.ISpriteInstance {},
	SineList: class extends self.IListInstance {},
	Movepoint: class extends self.ISpriteInstance {},
	MoveLine: class extends self.ITiledBackgroundInstance {},
	EditorPlus2: class extends self.ISpriteInstance {},
	EditAcc2: class extends self.ISpriteInstance {},
	EventList2: class extends self.IListInstance {},
	EditorEventBlock3: class extends self.ISpriteInstance {},
	EventList3: class extends self.IListInstance {},
	EditorCheck2: class extends self.ISpriteInstance {},
	EventFramList2: class extends self.IListInstance {},
	_99Bg: class extends self.ISpriteInstance {},
	EditorMenu: class extends self.ISpriteInstance {},
	EditorMenubutton: class extends self.ISpriteInstance {},
	EditorMenubutton2: class extends self.ISpriteInstance {},
	Lopaeditor: class extends self.ISpriteInstance {},
	StageNext: class extends self.ISpriteInstance {},
	StageImage2: class extends self.ISpriteInstance {},
	StageImage3: class extends self.ISpriteInstance {},
	desctext: class extends self.ISpriteFontInstance {},
	desctext3: class extends self.ISpriteFontInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	MovesetView: class extends self.ISpriteInstance {},
	Ost_Star: class extends self.ISpriteInstance {},
	Nube_pou: class extends self.ISpriteInstance {},
	Assist: class extends self.ISpriteInstance {},
	bossprob3: class extends self.ISpriteInstance {},
	Caca_pou: class extends self.ISpriteInstance {},
	Sprite105: class extends self.ISpriteInstance {},
	Sprite107: class extends self.ISpriteInstance {},
	Stage_Img4: class extends self.ISpriteInstance {},
	Stage_gptmon: class extends self.ISpriteInstance {},
	boss_prob7: class extends self.ISpriteInstance {},
	stage_space: class extends self.ISpriteInstance {},
	Sprite108: class extends self.ISpriteInstance {},
	st_polus_Trr: class extends self.ISpriteInstance {},
	st_float: class extends self.ISpriteInstance {},
	menuulock: class extends self.ISpriteInstance {},
	item_shield: class extends self.ISpriteInstance {},
	item_ball: class extends self.ISpriteInstance {},
	ob_luckyblock: class extends self.ISpriteInstance {},
	grasamenu: class extends self.ISpriteInstance {},
	st_ai: class extends self.ISpriteInstance {},
	TiledBackground28: class extends self.ITiledBackgroundInstance {},
	JSON: class extends self.IJSONInstance {},
	Family1: class extends self.ISpriteInstance {},
	roes: class extends self.ISpriteInstance {},
	Family2: class extends self.ISpriteInstance {},
	E_buttons: class extends self.ISpriteInstance {},
	Editor_Obj: class extends self.ISpriteInstance {},
	Family3: class extends self.ISpriteInstance {},
	Family4: class extends self.ISpriteInstance {}
}